In [1]:
from datetime import date

print(date.today())

2020-06-22


Different results for differnt tokenizer:

string = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."


In [7]:
string = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."


from nltk.tokenize import word_tokenize

print(word_tokenize(string))# Do // n't // Jone // 's' 

['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [8]:
from nltk.tokenize import WordPunctTokenizer

print(WordPunctTokenizer().tokenize(string)) # Don // ' // t // Jone // ' // s 

['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [9]:
from keras.preprocessing.text import text_to_word_sequence

print(text_to_word_sequence(string)) 
# all in small cases
# don't //  jone's

["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


Penn Treebank Tokenization

- Rule 1. keep as one word if a word is connected with '-'
- Rule 2. doesn't --> "does" + "n't" keep it as this format

In [10]:
string = "Starting a home-based restaurant may be an ideal. it doesn't have a food chain or restaurant of their own."

from nltk.tokenize import TreebankWordTokenizer

TreebankWordTokenizer().tokenize(string)

['Starting',
 'a',
 'home-based',
 'restaurant',
 'may',
 'be',
 'an',
 'ideal.',
 'it',
 'does',
 "n't",
 'have',
 'a',
 'food',
 'chain',
 'or',
 'restaurant',
 'of',
 'their',
 'own',
 '.']

#### sentence tokenize

binary classifier

- . is part of sentence, that is . is for abbreviation: ph.d.
- . is a end of a sentence

In [13]:
text="His barber kept his word. But keeping such a huge secret to himself was driving him crazy. Finally, the barber went up a mountain and almost to the edge of a cliff. He dug a hole in the midst of some reeds. He looked about, to mae sure no one was near."
text2="I am actively looking for Ph.D. students. and you are a Ph.D student."
from nltk.tokenize import sent_tokenize

print(sent_tokenize(text))
sent_tokenize(text2) # it does good job for ignoring . in ph.d.

['His barber kept his word.', 'But keeping such a huge secret to himself was driving him crazy.', 'Finally, the barber went up a mountain and almost to the edge of a cliff.', 'He dug a hole in the midst of some reeds.', 'He looked about, to mae sure no one was near.']


['I am actively looking for Ph.D. students.', 'and you are a Ph.D student.']

#### Cleaning & Normalization
    Cleaning : wipe out noise from corpus
        - 1. removing rare words
        - 2. removing words with very short length
    Normalization : unify words that have different expression means


*

    Causes the resulting RE to match 0 or more repetitions of the preceding RE, as many repetitions as are possible. ab* will match ‘a’, ‘ab’, or ‘a’ followed by any number of ‘b’s.


\b

    Matches the empty string, but only at the beginning or end of a word. A word is defined as a sequence of word characters. Note that formally, \b is defined as the boundary between a \w and a \W character (or vice versa), or between \w and the beginning/end of the string. This means that r'\bfoo\b' matches 'foo', 'foo.', '(foo)', 'bar foo baz' but not 'foobar' or 'foo3'.
    


\w

    For Unicode (str) patterns:

        Matches Unicode word characters; this includes most characters that can be part of a word in any language, as well as numbers and the underscore. If the ASCII flag is used, only [a-zA-Z0-9_] is matched.
    For 8-bit (bytes) patterns:

        Matches characters considered alphanumeric in the ASCII character set; this is equivalent to [a-zA-Z0-9_]. If the LOCALE flag is used, matches characters considered alphanumeric in the current locale and the underscore.

\W

    Matches any character which is not a word character. This is the opposite of \w. If the ASCII flag is used this becomes the equivalent of [^a-zA-Z0-9_]. If the LOCALE flag is used, matches characters which are neither alphanumeric in the current locale nor the underscore.


In [18]:
import re
text = "I was wondering if anyone out there could enlighten me on this car."
shortword = re.compile(r'\W*\b\w{1,2}\b')
print(shortword.sub('', text))

 was wondering anyone out there could enlighten this car.


#### Stemming & Lemmatization 


In [33]:
text = "This was not the map we found in Billy Bones's chest, but an accurate copy, complete in all things--names and heights and soundings--with the single exception of the red crosses and the written notes."

from nltk.stem import PorterStemmer, LancasterStemmer 
from nltk.tokenize import word_tokenize

words = word_tokenize(text)
print('tokenized words: \n', words)

#print('stems:', [PorterStemmer.stem(w) for w in word])
p= PorterStemmer()
print('Porter Stems: \n', [p.stem(w) for w in words])
l= LancasterStemmer()
print('Lancaster Stems: \n', [l.stem(w) for w in words])

tokenized words: 
 ['This', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'Billy', 'Bones', "'s", 'chest', ',', 'but', 'an', 'accurate', 'copy', ',', 'complete', 'in', 'all', 'things', '--', 'names', 'and', 'heights', 'and', 'soundings', '--', 'with', 'the', 'single', 'exception', 'of', 'the', 'red', 'crosses', 'and', 'the', 'written', 'notes', '.']
Porter Stems: 
 ['thi', 'wa', 'not', 'the', 'map', 'we', 'found', 'in', 'billi', 'bone', "'s", 'chest', ',', 'but', 'an', 'accur', 'copi', ',', 'complet', 'in', 'all', 'thing', '--', 'name', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'except', 'of', 'the', 'red', 'cross', 'and', 'the', 'written', 'note', '.']
Lancaster Stems: 
 ['thi', 'was', 'not', 'the', 'map', 'we', 'found', 'in', 'bil', 'bon', "'s", 'chest', ',', 'but', 'an', 'acc', 'cop', ',', 'complet', 'in', 'al', 'thing', '--', 'nam', 'and', 'height', 'and', 'sound', '--', 'with', 'the', 'singl', 'exceiv', 'of', 'the', 'red', 'cross', 'and', 'the', 'writ', 'no

In [21]:
words=['policies', 'doing', 'organizations', 'has', 'going', 'loves', 'lives', 'fly', 'dies', 'watched', 'science', 'starting']

from nltk.stem import WordNetLemmatizer

[WordNetLemmatizer().lemmatize(w) for w in words]

['policy',
 'doing',
 'organization',
 'ha',
 'going',
 'love',
 'life',
 'fly',
 'dy',
 'watched',
 'science',
 'starting']

#### Stopping words

In [35]:
from nltk.corpus import stopwords

stopwords.words('english')[:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [38]:
text = "Family is not an important thing. It's everything."

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

stop_words = set(stopwords.words('english'))

word_tk = word_tokenize(text)
print('before stopping words: \t', word_tk)


print('after stopping words: \t', [w for w in word_tk if w not in stop_words])

before stopping words: 	 ['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
after stopping words: 	 ['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


#### Regular Expression (re)

1) 정규 표현식 문법

정규 표현식을 위해 사용되는 문법 중 특수 문자들은 아래와 같습니다.
특수 문자 	설명
    . 	한 개의 임의의 문자를 나타냅니다. (줄바꿈 문자인 \n는 제외)
    ? 	앞의 문자가 존재할 수도 있고, 존재하지 않을 수도 있습니다. (문자가 0개 또는 1개)
    * 	앞의 문자가 무한개로 존재할 수도 있고, 존재하지 않을 수도 있습니다. (문자가 0개 이상)
    + 	앞의 문자가 최소 한 개 이상 존재합니다. (문자가 1개 이상)
    ^ 	뒤의 문자로 문자열이 시작됩니다.
    $ 	앞의 문자로 문자열이 끝납니다.
    {숫자} 	숫자만큼 반복합니다.
    {숫자1, 숫자2} 	숫자1 이상 숫자2 이하만큼 반복합니다. ?, *, +를 이것으로 대체할 수 있습니다.
    {숫자,} 	숫자 이상만큼 반복합니다.
    [ ] 	대괄호 안의 문자들 중 한 개의 문자와 매치합니다. [amk]라고 한다면 a 또는 m 또는 k 중 하나라도 존재하면 매치를 의미합니다. 
    [a-z]와 같이 범위를 지정할 수도 있습니다. [a-zA-Z]는 알파벳 전체를 의미하는 범위이며, 문자열에 알파벳이 존재하면 매치를 의미합니다.
    [^문자] 	해당 문자를 제외한 문자를 매치합니다.
    | 	AlB와 같이 쓰이며 A 또는 B의 의미를 가집니다.


문자 규칙 	설명
    \\ 	역 슬래쉬 문자 자체를 의미합니다
    \d 	모든 숫자를 의미합니다. [0-9]와 의미가 동일합니다.
    \D 	숫자를 제외한 모든 문자를 의미합니다. [^0-9]와 의미가 동일합니다.
    \s 	공백을 의미합니다. [ \t\n\r\f\v]와 의미가 동일합니다.
    \S 	공백을 제외한 문자를 의미합니다. [^ \t\n\r\f\v]와 의미가 동일합니다.
    \w 	문자 또는 숫자를 의미합니다. [a-zA-Z0-9]와 의미가 동일합니다.
    \W 	문자 또는 숫자가 아닌 문자를 의미합니다. [^a-zA-Z0-9]와 의미가 동일합니다.

2) 정규표현식 모듈 함수

정규표현식 모듈에서 지원하는 함수는 이와 같습니다.
    모듈 함수 	설명
    re.compile() 	정규표현식을 컴파일하는 함수입니다. 다시 말해, 파이썬에게 전해주는 역할을 합니다. 찾고자 하는 패턴이 빈번한 경우에는 미리 컴파일해놓고 사용하면 속도와 편의성면에서 유리합니다.
    
    re.search() 	문자열 전체에 대해서 정규표현식과 매치되는지를 검색합니다.
    
    re.match() 	문자열의 처음이 정규표현식과 매치되는지를 검색합니다.
    
    re.split() 	정규 표현식을 기준으로 문자열을 분리하여 리스트로 리턴합니다.
    
    re.findall() 	문자열에서 정규 표현식과 매치되는 모든 경우의 문자열을 찾아서 리스트로 리턴합니다. 만약, 매치되는 문자열이 없다면 빈 리스트가 리턴됩니다.
    
    re.finditer() 	문자열에서 정규 표현식과 매치되는 모든 경우의 문자열에 대한 이터레이터 객체를 리턴합니다.
    
    re.sub() 	문자열에서 정규 표현식과 일치하는 부분에 대해서 다른 문자열로 대체합니다.
    
**https://wikidocs.net/21703

In [44]:
text = "Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop"

from nltk.tokenize import RegexpTokenizer

# just get the words
tokenizer= RegexpTokenizer('[\w]+')
tk = tokenizer.tokenize(text)
print(tk)

import re 
reg = re.findall(r'\w+', text)

tk == reg

['Don', 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'Mr', 'Jone', 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


True

In [45]:
tokenizer= RegexpTokenizer('[\s]+', gaps= True)
tk = tokenizer.tokenize(text)
print(tk)

["Don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name,', 'Mr.', "Jone's", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


#### Int Encoding 

In [46]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

# sent_tokenize
txt = sent_tokenize(text)
txt

['A barber is a person.',
 'a barber is good person.',
 'a barber is huge person.',
 'he Knew A Secret!',
 'The Secret He Kept is huge secret.',
 'Huge secret.',
 'His barber kept his word.',
 'a barber kept his word.',
 'His barber kept his secret.',
 'But keeping and keeping such a huge secret to himself was driving the barber crazy.',
 'the barber went up a huge mountain.']

In [55]:
# cleaning and tokenizing

vocab = {}
sentences =[]
sw = set(stopwords.words('english'))

for i in txt:
    sentence = word_tokenize(i) # tokenize
    result =[]
    
    for word in sentence: 
        word = word.lower() #lowercase
        
        if word not in sw:
            if(len(word)) > 2: #remove very short words
                result.append(word)
                
                if word not in vocab:
                    vocab[word] = 0
                    
                vocab[word] += 1 # ++ the count for each words
    
    sentences.append(result)
    
sentences, vocab

([['barber', 'person'],
  ['barber', 'good', 'person'],
  ['barber', 'huge', 'person'],
  ['knew', 'secret'],
  ['secret', 'kept', 'huge', 'secret'],
  ['huge', 'secret'],
  ['barber', 'kept', 'word'],
  ['barber', 'kept', 'word'],
  ['barber', 'kept', 'secret'],
  ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
  ['barber', 'went', 'huge', 'mountain']],
 {'barber': 8,
  'person': 3,
  'good': 1,
  'huge': 5,
  'knew': 1,
  'secret': 6,
  'kept': 4,
  'word': 2,
  'keeping': 2,
  'driving': 1,
  'crazy': 1,
  'went': 1,
  'mountain': 1})

In [56]:
sorted_vocab = sorted(vocab.items(), key= lambda x:x[1], reverse = True)
sorted_vocab

[('barber', 8),
 ('secret', 6),
 ('huge', 5),
 ('kept', 4),
 ('person', 3),
 ('word', 2),
 ('keeping', 2),
 ('good', 1),
 ('knew', 1),
 ('driving', 1),
 ('crazy', 1),
 ('went', 1),
 ('mountain', 1)]

In [60]:
# make the barber = 1 
word_ind ={}
i =0
for word, freq in sorted_vocab:
    if freq > 1: # remove words that apreas less than 1
        i += 1
        word_ind[word] = i
        
word_ind

{'barber': 1,
 'secret': 2,
 'huge': 3,
 'kept': 4,
 'person': 5,
 'word': 6,
 'keeping': 7}

In [65]:
# get the top n
top_n = 5 # barber ~ person // del word & keeping

del_word = [w for w,f in word_ind.items() if f >= top_n +1]
del_word

for w in del_word:
    del word_ind[w]
    
word_ind

#[w for w, f in word_ind.items() if f <= top_n +1]

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}

In [66]:
# creat out of vocab for the rest of the words
word_ind['OOV'] = len(word_ind)+1
word_ind

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5, 'OOV': 6}

In [67]:
# int encoding 
encode=[]
for s in sentences: 
    temp=[]
    
    for w in s: 
        try:
            temp.append(word_ind[w])
        except KeyError:
            temp.append(word_ind['OOV'])
    
    encode.append(temp)

encode

[[1, 5],
 [1, 6, 5],
 [1, 3, 5],
 [6, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [6, 6, 3, 2, 6, 1, 6],
 [1, 6, 3, 6]]

In [79]:
# instead of using dictionary this could be done faster via Counter 

from collections import Counter

words = sum(sentences, []) #force into one list
vocab = Counter(words)

vocab

Counter({'barber': 8,
         'person': 3,
         'good': 1,
         'huge': 5,
         'knew': 1,
         'secret': 6,
         'kept': 4,
         'word': 2,
         'keeping': 2,
         'driving': 1,
         'crazy': 1,
         'went': 1,
         'mountain': 1})

In [80]:
top_n = 5
top_vocabs = vocab.most_common(top_n) # most_common will return the top N 
top_vocabs

[('barber', 8), ('secret', 6), ('huge', 5), ('kept', 4), ('person', 3)]

In [82]:
word_ind ={}
i =0

for w, f in top_vocabs:
    i+=1
    word_ind[w] = i

word_ind

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}

In [93]:
# this time use nltk FreqDist

from nltk import FreqDist
import numpy as np

word = np.hstack(sentences)
vocab = FreqDist(word)

vocab

# get the topN
top_vocabs = vocab.most_common(top_n)
top_vocabs

# reversing the order
word_ind = {w[0] : i+1 for i, w in enumerate(top_vocabs)}
word_ind

{'barber': 1, 'secret': 2, 'huge': 3, 'kept': 4, 'person': 5}

In [110]:
# keras 
from keras.preprocessing.text import Tokenizer
print(sentences)

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences) # this does int encoding automatically 
tokenizer.word_index

[['barber', 'person'], ['barber', 'good', 'person'], ['barber', 'huge', 'person'], ['knew', 'secret'], ['secret', 'kept', 'huge', 'secret'], ['huge', 'secret'], ['barber', 'kept', 'word'], ['barber', 'kept', 'word'], ['barber', 'kept', 'secret'], ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'], ['barber', 'went', 'huge', 'mountain']]


{'barber': 1,
 'secret': 2,
 'huge': 3,
 'kept': 4,
 'person': 5,
 'word': 6,
 'keeping': 7,
 'good': 8,
 'knew': 9,
 'driving': 10,
 'crazy': 11,
 'went': 12,
 'mountain': 13}

In [111]:
# to see the counts for each words
tokenizer.word_counts

OrderedDict([('barber', 8),
             ('person', 3),
             ('good', 1),
             ('huge', 5),
             ('knew', 1),
             ('secret', 6),
             ('kept', 4),
             ('word', 2),
             ('keeping', 2),
             ('driving', 1),
             ('crazy', 1),
             ('went', 1),
             ('mountain', 1)])

In [112]:
tokenizer.texts_to_sequences(sentences)

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [121]:
# keras will delete OOV automatically.. so if i want to keep the oov words 
top_n = 5
tokenizer = Tokenizer(num_words = top_n + 2, # since there are 0 and 'oov', i need to add 2
                      oov_token= 'OOV') # OOV index will be 1!!

tokenizer.fit_on_texts(sentences)

f'in Keras the index of OOV is %d' %(tokenizer.word_index['OOV'])

tokenizer.texts_to_sequences(sentences)

[[2, 6],
 [2, 1, 6],
 [2, 4, 6],
 [1, 3],
 [3, 5, 4, 3],
 [4, 3],
 [2, 5, 1],
 [2, 5, 1],
 [2, 5, 3],
 [1, 1, 4, 3, 1, 2, 1],
 [2, 1, 4, 1]]

#### Padding

1. tokenizer = Tokenizer()
2. tokenizer.fit_on_texts(sentences)
3. encoded = tokenizer.texts_to_sequences(sentences)

In [122]:
import numpy as np
from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

encoded = tokenizer.texts_to_sequences(sentences)
print(encoded)

# as a preperation for modeling i need to have them all in same length!

[[1, 5], [1, 8, 5], [1, 3, 5], [9, 2], [2, 4, 3, 2], [3, 2], [1, 4, 6], [1, 4, 6], [1, 4, 2], [7, 7, 3, 2, 10, 1, 11], [1, 12, 3, 13]]


In [123]:
max_len = max(len(i) for i in encoded)

#post padding
for i in encoded: 
    while len(i) < max_len:
        i.append(0)

padded_np = np.array(encoded)
padded_np

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [124]:
# Using keras pad_sequences

from keras.preprocessing.sequence import pad_sequences

encoded = tokenizer.texts_to_sequences(sentences)

pre_pad = pad_sequences(encoded)
pre_pad

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]])

In [125]:
post_pad = pad_sequences(encoded, padding='post')
post_pad

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]])

In [127]:
last_val = len(tokenizer.word_index) + 1

padded = pad_sequences(encoded, 
                       padding='post', 
                       maxlen= 5,
                       value = last_val) # 
padded

array([[ 1,  5, 14, 14, 14],
       [ 1,  8,  5, 14, 14],
       [ 1,  3,  5, 14, 14],
       [ 9,  2, 14, 14, 14],
       [ 2,  4,  3,  2, 14],
       [ 3,  2, 14, 14, 14],
       [ 1,  4,  6, 14, 14],
       [ 1,  4,  6, 14, 14],
       [ 1,  4,  2, 14, 14],
       [ 3,  2, 10,  1, 11],
       [ 1, 12,  3, 13, 14]])

#### One hot Encoding

In [132]:
text = 'Would  you like to go have burger for lunch with me? The burger is really good'
text

'Would  you like to go have burger for lunch with me? The burger is really good'

In [133]:
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical

t = Tokenizer()
t.fit_on_texts([text])
t.word_index

{'burger': 1,
 'would': 2,
 'you': 3,
 'like': 4,
 'to': 5,
 'go': 6,
 'have': 7,
 'for': 8,
 'lunch': 9,
 'with': 10,
 'me': 11,
 'the': 12,
 'is': 13,
 'really': 14,
 'good': 15}

In [135]:
sub_text = 'would you like to go have really good burger for lunch with me'

encoded = t.texts_to_sequences([sub_text])
encoded

[[2, 3, 4, 5, 6, 7, 14, 15, 1, 8, 9, 10, 11]]

In [136]:
one_hot = to_categorical(encoded)
one_hot 

array([[[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]],
      dtype=float32)

One hot encoding demand high memory for increasing the dimensions, also cannot capture latent similarity between words. This could be remedied by 
    1. vectorlization : LSA, HAL, etc
    2. prediction based vectorization: NNLM, RNNLM, Word2Vec, FastText, etc
    3. Glove

BPE 

In [137]:
#dictionary = {'low' : 5, 'lower' : 2, 'newest' : 6, 'widest' : 3}

import re, collections 

num_merge = 10
vocab = {'l o w </w>' : 5,
         'l o w e r </w>' : 2,
         'n e w e s t </w>':6,
         'w i d e s t </w>':3
         }
vocab

{'l o w </w>': 5,
 'l o w e r </w>': 2,
 'n e w e s t </w>': 6,
 'w i d e s t </w>': 3}

In [139]:
def get_stats(vocab):
    pairs = collections.defaultdict(int)
    for word, freq in vocab.items():
        symbols = word.split()
        for i in range(len(symbols)-1):
            pairs[symbols[i],symbols[i+1]] += freq
    return pairs

def merge_vocab(pair, v_in):
    v_out = {}
    bigram = re.escape(' '.join(pair))
    p = re.compile(r'(?<!\S)' + bigram + r'(?!\S)')
    for word in v_in:
        w_out = p.sub(''.join(pair), word)
        v_out[w_out] = v_in[word]
    return v_out

for i in range(num_merge):
    pairs = get_stats(vocab)
    best = max(pairs, key=pairs.get)
    vocab = merge_vocab(best, vocab)
    print(best)

('e', 's')
('es', 't')
('est', '</w>')
('l', 'o')
('lo', 'w')
('n', 'e')
('ne', 'w')
('new', 'est</w>')
('low', '</w>')
('w', 'i')


### Bag of Words (BoW)

In [143]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ['you know I want your love. Because I love you']
vector = CountVectorizer()
# this automatically picks up words with length > 2; it tokenizes based on space

print(vector.fit_transform(corpus).toarray())
print(vector.vocabulary_)

[[1 1 2 1 2 1]]
{'you': 4, 'know': 1, 'want': 3, 'your': 5, 'love': 2, 'because': 0}


In [144]:
text=["Family is not an important thing. It's everything."]

vector = CountVectorizer(stop_words=['is', 'an', 'the', 'a']) # or i can use stop_words = 'english'
print(vector.fit_transform(text).toarray())
print(vector.vocabulary_)

[[1 1 1 1 1 1]]
{'family': 1, 'not': 4, 'important': 2, 'thing': 5, 'it': 3, 'everything': 0}


In [146]:
from nltk.corpus import stopwords
text=["Family is not an important thing. It's everything."]

sw = stopwords.words('english')
vector = CountVectorizer(stop_words='english')
vector_nltk = CountVectorizer(stop_words= sw)
print(vector.fit_transform(text).toarray())
print(vector.vocabulary_)

print(vector_nltk.fit_transform(text).toarray())
print(vector_nltk.vocabulary_)

[[1 1 1]]
{'family': 0, 'important': 1, 'thing': 2}
[[1 1 1 1]]
{'family': 1, 'important': 2, 'thing': 3, 'everything': 0}


### TF-IDF

In [157]:
docs = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]
vocab = list(set(w for doc in docs for w in doc.split()))
vocab.sort()
vocab

['I', 'do', 'know', 'like', 'love', 'should', 'want', 'what', 'you', 'your']

In [158]:
N = len(docs)

def tf(t, d):
    return d.count(t)

def idf(t):
    df = 0
    for doc in docs: 
        df += t in doc
    return np.log(N / (df+1))

def tfidf(t,d):
    return tf(t,d) * idf(t)


In [159]:
import pandas as pd
result =[]

for i in range(N):
    result.append([])
    d = docs[i]
    
    for j in range(len(vocab)):
        t = vocab[j]
        result[-1].append(tf(t,d))

# DTM
tf_ = pd.DataFrame(result, columns= vocab)
tf_

I  do  know  like  love  should  want  what  you  your
0  1   0     1     0     1       0     1     0    2     1
1  1   0     0     1     0       0     0     0    1     0
2  1   1     0     0     0       1     0     1    0     0

In [160]:
result = []
for i in range(len(vocab)):
    t = vocab[i]
    
    result.append(idf(t))

idf_ = pd.DataFrame(result, index = vocab, columns=['idf'])
idf_

idf
I      -0.287682
do      0.405465
know    0.405465
like    0.405465
love    0.405465
should  0.405465
want    0.405465
what    0.405465
you     0.000000
your    0.405465

In [161]:
result =[]

for i in range(N):
    result.append([])
    d = docs[i]
    
    for j in range(len(vocab)):
        t = vocab[j]
        
        result[-1].append(tfidf(t,d))

tfidf_ = pd.DataFrame(result, columns= vocab)
tfidf_

I        do      know      like      love    should      want      what  you      your
0 -0.287682  0.000000  0.405465  0.000000  0.405465  0.000000  0.405465  0.000000  0.0  0.405465
1 -0.287682  0.000000  0.000000  0.405465  0.000000  0.000000  0.000000  0.000000  0.0  0.000000
2 -0.287682  0.405465  0.000000  0.000000  0.000000  0.405465  0.000000  0.405465  0.0  0.000000

In [156]:
# using sklearn

from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'you know I want your love',
    'I like you',
    'what should I do ',    
]

tfidf = TfidfVectorizer().fit(corpus)
print(tfidf.transform(corpus).toarray())
print(tfidf.vocabulary_)

[[0.         0.46735098 0.         0.46735098 0.         0.46735098
  0.         0.35543247 0.46735098]
 [0.         0.         0.79596054 0.         0.         0.
  0.         0.60534851 0.        ]
 [0.57735027 0.         0.         0.         0.57735027 0.
  0.57735027 0.         0.        ]]
{'you': 7, 'know': 1, 'want': 5, 'your': 8, 'love': 3, 'like': 2, 'what': 6, 'should': 4, 'do': 0}


Very simple recommendation 

In [164]:
import pandas as pd
import os 

os.listdir('../data')

['1069_1940_compressed_PS_20174392719_1491204439457_log.csv.zip',
 '3405_6663_bundle_archive.zip',
 'iris.data.csv']

In [166]:
#dat = pd.read_csv('../data/3405_6663_bundle_archive.zip')

from zipfile import ZipFile 
  
# specifying the zip file name 
file_name = "../data/3405_6663_bundle_archive.zip"
  

with ZipFile(file_name, 'r') as zip: 
    zip.printdir() 
  
    print('Extracting all the files now...') 
    zip.extractall() 
    print('Done!') 

File Name                                             Modified             Size
credits.csv                                    2019-09-21 10:29:08    189917659
keywords.csv                                   2019-09-21 10:29:24      6231943
links.csv                                      2019-09-21 10:29:24       989107
links_small.csv                                2019-09-21 10:29:24       183372
movies_metadata.csv                            2019-09-21 10:29:24     34445126
ratings.csv                                    2019-09-21 10:29:28    709550327
ratings_small.csv                              2019-09-21 10:30:38      2438266
Extracting all the files now...
Done!


In [175]:
dat = pd.read_csv("movies_metadata.csv")

In [176]:
dat = dat[:20000]

In [177]:
dat.isnull().sum(axis= 0)

adult                        0
belongs_to_collection    17601
budget                       0
genres                       0
homepage                 16945
id                           0
imdb_id                      7
original_language            1
original_title               0
overview                   135
popularity                   2
poster_path                 93
production_companies         1
production_countries         1
release_date                17
revenue                      2
runtime                     29
spoken_languages             2
status                      21
tagline                   8294
title                        2
video                        2
vote_average                 2
vote_count                   2
dtype: int64

In [178]:
dat['overview'] = dat['overview'].fillna('')

In [179]:
dat['overview'].isnull().sum()

0

In [181]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(dat['overview'])

tfidf_matrix.shape

(20000, 47487)

In [182]:
from sklearn.metrics.pairwise import linear_kernel
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim

array([[1.        , 0.01575748, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01575748, 1.        , 0.04907345, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.04907345, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.08375766],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.08375766, 0.        ,
        1.        ]])

In [184]:
indices = pd.Series(dat.index, index = dat['title']).drop_duplicates()
indices.head()

title
Toy Story                      0
Jumanji                        1
Grumpier Old Men               2
Waiting to Exhale              3
Father of the Bride Part II    4
dtype: int64

In [187]:
def get_recommendations(title, cosine_sim=cosine_sim):
    idx = indices[title]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    #top10
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]

    return dat['title'].iloc[movie_indices]

In [188]:
get_recommendations('Toy Story')

15348               Toy Story 3
2997                Toy Story 2
10301    The 40 Year Old Virgin
8327                  The Champ
1071      Rebel Without a Cause
11399    For Your Consideration
1932                  Condorman
3057            Man on the Moon
485                      Malice
11606              Factory Girl
Name: title, dtype: object

#### SVD with Twenty Newsgroups

In [193]:
import pandas as pd
import numpy as np

from sklearn.datasets import fetch_20newsgroups

dat = fetch_20newsgroups(shuffle = True, random_state = 1, remove = ('headers', 'footers', 'quotes'))
documents = dat.data

len(documents)

11314

In [194]:
documents[1]

"\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n\n\n\n\n\n\nJim,\n\nSorry I can't pity you, Jim.  And I'm sorry that you have these feelings of\ndenial about the faith you need to get by.  Oh well, just pretend that it will\nall end happily ever after anyway.  Maybe if you start a new newsgroup,\nalt.atheist.hard, you won't be bummin' so much?\n\n\n\n\n\n\nBye-Bye, Big Jim.  Don't forget your Flintstone's Chewables!  :) \n--\nBake Timmons, III"

In [197]:
dat.target_names

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']

In [200]:
# Cleaning the data

df = pd.DataFrame({'documents': documents})

# delete anything not an alphabet
df['clean_doc'] = df['documents'].str.replace('[^a-zA-Z]', ' ')

# removing characters shorter than 3
df['clean_doc'] = df['clean_doc'].apply(lambda x:' '.join([w for w in x.split() if len(w) >3]))

# lower case
df['clean_doc'] = df['clean_doc'].apply(lambda x: x.lower())

In [201]:
df['clean_doc'][1]

'yeah expect people read actually accept hard atheism need little leap faith jimmy your logic runs steam sorry pity sorry that have these feelings denial about faith need well just pretend that will happily ever after anyway maybe start newsgroup atheist hard bummin much forget your flintstone chewables bake timmons'

In [202]:
# comparing with the pre-cleaning: 
documents[1]

"\n\n\n\n\n\n\nYeah, do you expect people to read the FAQ, etc. and actually accept hard\natheism?  No, you need a little leap of faith, Jimmy.  Your logic runs out\nof steam!\n\n\n\n\n\n\n\nJim,\n\nSorry I can't pity you, Jim.  And I'm sorry that you have these feelings of\ndenial about the faith you need to get by.  Oh well, just pretend that it will\nall end happily ever after anyway.  Maybe if you start a new newsgroup,\nalt.atheist.hard, you won't be bummin' so much?\n\n\n\n\n\n\nBye-Bye, Big Jim.  Don't forget your Flintstone's Chewables!  :) \n--\nBake Timmons, III"

In [205]:
# stopwords 

from nltk.corpus import stopwords
sw = stopwords.words("english")

# tokenizing
tokenized_doc = df['clean_doc'].apply(lambda x: x.split())
#tokenized_doc
# removing stopwords
tokenized_doc = tokenized_doc.apply(lambda x: [w for w in x if w not in sw])
tokenized_doc[1]

['yeah',
 'expect',
 'people',
 'read',
 'actually',
 'accept',
 'hard',
 'atheism',
 'need',
 'little',
 'leap',
 'faith',
 'jimmy',
 'logic',
 'runs',
 'steam',
 'sorry',
 'pity',
 'sorry',
 'feelings',
 'denial',
 'faith',
 'need',
 'well',
 'pretend',
 'happily',
 'ever',
 'anyway',
 'maybe',
 'start',
 'newsgroup',
 'atheist',
 'hard',
 'bummin',
 'much',
 'forget',
 'flintstone',
 'chewables',
 'bake',
 'timmons']

In [206]:
# to use tfidf need to detokenize the doc again

detoken_doc =[]
for i in range(len(df)):
    t = ' '.join(tokenized_doc[i])
    detoken_doc.append(t)
    
detoken_doc[1]

'yeah expect people read actually accept hard atheism need little leap faith jimmy logic runs steam sorry pity sorry feelings denial faith need well pretend happily ever anyway maybe start newsgroup atheist hard bummin much forget flintstone chewables bake timmons'

In [207]:
df['clean_doc'] = detoken_doc

In [208]:
# applying TfidfVectorizer to 1,000 words

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words= 'english', 
                             max_features= 1000, 
                             max_df= 0.5, 
                             smooth_idf= True)

X = vectorizer.fit_transform(df['clean_doc'])
X.shape

(11314, 1000)

In [209]:
# Topic Model with 20 topics by using SVD (SVD = U, s, VT)

from sklearn.decomposition import TruncatedSVD

svd_model = TruncatedSVD(n_components=20, 
                         algorithm= 'randomized', 
                         n_iter= 100, 
                         random_state= 42)

svd_model.fit(X)
len(svd_model.components_) # VT

20

In [210]:
np.shape(svd_model.components_) # 20 topics with 1000 words!

(20, 1000)

In [211]:
terms = vectorizer.get_feature_names() #storing 1000 words 

def get_topics(components, feature_names, n = 5):
    for idx, topic in enumerate(components):
        print("Topic %d:" % (idx+1), [(feature_names[i], topic[i].round(5)) for i in topic.argsort()[:-n - 1:-1]])
        
get_topics(svd_model.components_, terms)

Topic 1: [('like', 0.21386), ('know', 0.20046), ('people', 0.19293), ('think', 0.17805), ('good', 0.15128)]
Topic 2: [('thanks', 0.32888), ('windows', 0.29088), ('card', 0.18069), ('drive', 0.17455), ('mail', 0.15111)]
Topic 3: [('game', 0.37064), ('team', 0.32443), ('year', 0.28154), ('games', 0.2537), ('season', 0.18419)]
Topic 4: [('drive', 0.53324), ('scsi', 0.20165), ('hard', 0.15628), ('disk', 0.15578), ('card', 0.13994)]
Topic 5: [('windows', 0.40399), ('file', 0.25436), ('window', 0.18044), ('files', 0.16078), ('program', 0.13894)]
Topic 6: [('chip', 0.16114), ('government', 0.16009), ('mail', 0.15625), ('space', 0.1507), ('information', 0.13562)]
Topic 7: [('like', 0.67086), ('bike', 0.14236), ('chip', 0.11169), ('know', 0.11139), ('sounds', 0.10371)]
Topic 8: [('card', 0.46633), ('video', 0.22137), ('sale', 0.21266), ('monitor', 0.15463), ('offer', 0.14643)]
Topic 9: [('know', 0.46047), ('card', 0.33605), ('chip', 0.17558), ('government', 0.1522), ('video', 0.14356)]
Topic 10

#### LDA

In [212]:
tokenized_doc[:5]

0    [well, sure, story, seem, biased, disagree, st...
1    [yeah, expect, people, read, actually, accept,...
2    [although, realize, principle, strongest, poin...
3    [notwithstanding, legitimate, fuss, proposal, ...
4    [well, change, scoring, playoff, pool, unfortu...
Name: clean_doc, dtype: object

In [215]:
#pip install --upgrade gensim

  Stored in directory: C:\Users\caffr\AppData\Local\pip\Cache\wheels\27\65\38\8d7f5fe8d7afb4e4566587b2d1933cec185fba19257836c943
Successfully built smart-open
  Found existing installation: Cython 0.29.6
    Uninstalling Cython-0.29.6:
      Successfully uninstalled Cython-0.29.6
Note: you may need to restart the kernel to use updated packages.


In [216]:
# int encoding and get the freq of each word

from gensim import corpora 
dictionary = corpora.Dictionary(tokenized_doc)

corpus = [dictionary.doc2bow(text) for text in tokenized_doc]
corpus[1]

C:\Users\caffr\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


[(52, 1),
 (55, 1),
 (56, 1),
 (57, 1),
 (58, 1),
 (59, 1),
 (60, 1),
 (61, 1),
 (62, 1),
 (63, 1),
 (64, 1),
 (65, 1),
 (66, 2),
 (67, 1),
 (68, 1),
 (69, 1),
 (70, 1),
 (71, 2),
 (72, 1),
 (73, 1),
 (74, 1),
 (75, 1),
 (76, 1),
 (77, 1),
 (78, 2),
 (79, 1),
 (80, 1),
 (81, 1),
 (82, 1),
 (83, 1),
 (84, 1),
 (85, 2),
 (86, 1),
 (87, 1),
 (88, 1),
 (89, 1)]

In [219]:
print(dictionary[66])
print(len(dictionary))

faith
64281


In [220]:
import gensim 

num_topics = 20
ldamodel = gensim.models.ldamodel.LdaModel(corpus, 
                                           num_topics=num_topics, 
                                           id2word=dictionary, 
                                           passes = 15) # num of iteration

topics = ldamodel.print_topics(num_words = 4)

for topic in topics: 
    print(topic)

(0, '0.006*"people" + 0.005*"guns" + 0.004*"many" + 0.004*"control"')
(1, '0.013*"jesus" + 0.009*"believe" + 0.008*"people" + 0.008*"christian"')
(2, '0.032*"water" + 0.008*"plants" + 0.008*"cooling" + 0.008*"plant"')
(3, '0.026*"president" + 0.012*"going" + 0.011*"jobs" + 0.010*"think"')
(4, '0.011*"windows" + 0.011*"drive" + 0.011*"would" + 0.010*"know"')
(5, '0.039*"window" + 0.022*"motif" + 0.019*"widget" + 0.019*"server"')
(6, '0.013*"israel" + 0.012*"armenian" + 0.011*"jews" + 0.010*"turkish"')
(7, '0.019*"would" + 0.010*"people" + 0.008*"think" + 0.008*"like"')
(8, '0.013*"cover" + 0.009*"title" + 0.008*"copies" + 0.007*"crash"')
(9, '0.008*"health" + 0.006*"national" + 0.006*"april" + 0.006*"information"')
(10, '0.023*"game" + 0.021*"team" + 0.018*"year" + 0.016*"games"')
(11, '0.023*"sale" + 0.017*"offer" + 0.016*"condition" + 0.015*"shipping"')
(12, '0.028*"file" + 0.018*"program" + 0.014*"output" + 0.013*"files"')
(13, '0.012*"pain" + 0.011*"picture" + 0.007*"judas" + 0.004*

In [222]:
#!pip install pyLDAvis

  Stored in directory: C:\Users\caffr\AppData\Local\pip\Cache\wheels\98\71\24\513a99e58bb6b8465bae4d2d5e9dba8f0bef8179e3051ac414
  Stored in directory: C:\Users\caffr\AppData\Local\pip\Cache\wheels\20\5a\d8\1d875df03deae6f178dfdf70238cca33f948ef8a6f5209f2eb
Successfully built pyLDAvis funcy
Note: you may need to restart the kernel to use updated packages.


In [226]:
#visualizing lda model 
import pyLDAvis.gensim 

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(ldamodel, corpus, dictionary)

C:\Users\caffr\Anaconda3\lib\site-packages\pyLDAvis\_prepare.py:257: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  return pd.concat([default_term_info] + list(topic_dfs))


NameError: name 'pyLADvis' is not defined

In [227]:
pyLDAvis.display(vis)

Here, circles represents 20 topics. And the distance btw the circles means how much a topic is different from the others. If two circles overlap then the topics are overlapping. 

In [229]:
for i, topic_list in enumerate(ldamodel[corpus]):
    if i == 5: 
        break 
    print(i, 'th documents topic is: ', topic_list)

0 th documents topic is:  [(0, 0.13395585), (1, 0.10933098), (6, 0.31871432), (7, 0.28932667), (8, 0.018454913), (12, 0.11870777)]
1 th documents topic is:  [(1, 0.30886817), (2, 0.027623694), (7, 0.6002353), (10, 0.042196106)]
2 th documents topic is:  [(1, 0.16538571), (6, 0.26848772), (7, 0.4159749), (16, 0.13720335)]
3 th documents topic is:  [(4, 0.12732254), (7, 0.8091132), (9, 0.022848625), (12, 0.027999116)]
4 th documents topic is:  [(10, 0.39591396), (14, 0.57074046)]


In [228]:
def make_topictable_per_doc(ldamodel, corpus):
    topic_table = pd.DataFrame()

    
    for i, topic_list in enumerate(ldamodel[corpus]):
        doc = topic_list[0] if ldamodel.per_word_topics else topic_list            
        # sort the documents by weights of topics
        doc = sorted(doc, key=lambda x: (x[1]), reverse=True)
        
        
        # applying to all the docs
        for j, (topic_num, prop_topic) in enumerate(doc): #  store the topic number and its weigths
            if j == 0:  # since its already sorted the left is the most important(weighted) topic
                topic_table = topic_table.append(pd.Series([int(topic_num), round(prop_topic,4), topic_list]), 
                                                 ignore_index=True)
            else:
                break
    return(topic_table)

In [230]:
topictab = make_topictable_per_doc(ldamodel, corpus)
topictab = topictab.reset_index()
topictab.columns = ['doc_#', 'Most weighted Topic', 'Topic Weights', 'Weights']
topictab[:10]

doc_#  Most weighted Topic  Topic Weights                                            Weights
0      0                  6.0         0.3187  [(0, 0.13396183), (1, 0.109256946), (6, 0.3187...
1      1                  7.0         0.6002  [(1, 0.30891076), (2, 0.027623694), (7, 0.6002...
2      2                  7.0         0.4159  [(1, 0.16541779), (6, 0.2684898), (7, 0.415893...
3      3                  7.0         0.8090  [(4, 0.12699461), (7, 0.80902475), (9, 0.02327...
4      4                 14.0         0.5707                [(10, 0.39593396), (14, 0.5707205)]
5      5                  7.0         0.4618  [(1, 0.2686706), (3, 0.07334986), (7, 0.461804...
6      6                  4.0         0.5397  [(0, 0.16975811), (3, 0.018858196), (4, 0.5397...
7      7                  7.0         0.4462  [(1, 0.086775295), (5, 0.035179533), (6, 0.300...
8      8                  7.0         0.4886  [(2, 0.18689574), (3, 0.18662259), (7, 0.48857...
9      9                 14.0         0.4153  [(4, 0.1548003), (6, 0.013576224), (7, 0.20823...

#### LDA 2

In [231]:
import pandas as pd
import urllib.request
urllib.request.urlretrieve("https://raw.githubusercontent.com/franciscadias/data/master/abcnews-date-text.csv", filename="abcnews-date-text.csv")
data = pd.read_csv('abcnews-date-text.csv', error_bad_lines=False)

In [232]:
data.head()

publish_date                                      headline_text
0      20030219  aba decides against community broadcasting lic...
1      20030219     act fire witnesses must be aware of defamation
2      20030219     a g calls for infrastructure protection summit
3      20030219           air nz staff in aust strike for pay rise
4      20030219      air nz strike to affect australian travellers

In [238]:
text = data[['headline_text']]
text.head()

headline_text
0  aba decides against community broadcasting lic...
1     act fire witnesses must be aware of defamation
2     a g calls for infrastructure protection summit
3           air nz staff in aust strike for pay rise
4      air nz strike to affect australian travellers

In [239]:
# preprocess: stopwords, [^a-zA-Z], short words

import nltk
text['headline_text'] = text.apply(lambda row: nltk.word_tokenize(row['headline_text']), axis=1)

C:\Users\caffr\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [240]:
text.head()

headline_text
0  [aba, decides, against, community, broadcastin...
1  [act, fire, witnesses, must, be, aware, of, de...
2  [a, g, calls, for, infrastructure, protection,...
3  [air, nz, staff, in, aust, strike, for, pay, r...
4  [air, nz, strike, to, affect, australian, trav...

In [241]:
from nltk.corpus import stopwords
sw = stopwords.words('english')

text['headline_text'] = text['headline_text'].apply(lambda x: [word for word in x if word not in sw])
text.head()

C:\Users\caffr\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


headline_text
0   [aba, decides, community, broadcasting, licence]
1    [act, fire, witnesses, must, aware, defamation]
2     [g, calls, infrastructure, protection, summit]
3          [air, nz, staff, aust, strike, pay, rise]
4  [air, nz, strike, affect, australian, travellers]

In [242]:
from nltk.stem import WordNetLemmatizer

text['headline_text'] = text['headline_text'].apply(lambda x: [WordNetLemmatizer().lemmatize(word, pos='v') for word in x])
text.head()

C:\Users\caffr\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


headline_text
0       [aba, decide, community, broadcast, licence]
1      [act, fire, witness, must, aware, defamation]
2      [g, call, infrastructure, protection, summit]
3          [air, nz, staff, aust, strike, pay, rise]
4  [air, nz, strike, affect, australian, travellers]

In [243]:
tokenized_doc = text['headline_text'].apply(lambda x: [word for word in x if len(word) > 3])
tokenized_doc[:5]

0       [decide, community, broadcast, licence]
1      [fire, witness, must, aware, defamation]
2    [call, infrastructure, protection, summit]
3                   [staff, aust, strike, rise]
4      [strike, affect, australian, travellers]
Name: headline_text, dtype: object

In [244]:
detokenized_doc = []
for i in range(len(text)):
    t = ' '.join(tokenized_doc[i])
    detokenized_doc.append(t)

text['headline_text'] = detokenized_doc 

C:\Users\caffr\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [245]:
text['headline_text'][:5]

0       decide community broadcast licence
1       fire witness must aware defamation
2    call infrastructure protection summit
3                   staff aust strike rise
4      strike affect australian travellers
Name: headline_text, dtype: object

In [248]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english', 
                            max_features = 1000)

X = vectorizer.fit_transform(text['headline_text'])
X.shape

(1082168, 1000)

In [249]:
# modeling

from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components= 10, 
                                     learning_method='online', 
                                     random_state=42,
                                     max_iter= 1)

In [250]:
lda_top = lda_model.fit_transform(X)

AttributeError: 'numpy.ndarray' object has no attribute 'components_'

In [254]:
lda_top

array([[0.03669227, 0.03669227, 0.03669227, ..., 0.48500584, 0.03669227,
        0.03669227],
       [0.05      , 0.05      , 0.05      , ..., 0.55      , 0.05      ,
        0.05      ],
       [0.25184311, 0.03660966, 0.03660966, ..., 0.03660966, 0.03660966,
        0.03660966],
       ...,
       [0.03663014, 0.24045712, 0.26244076, ..., 0.03663014, 0.03663014,
        0.03663014],
       [0.23295112, 0.03354632, 0.03354632, ..., 0.20853926, 0.03354632,
        0.32368536],
       [0.05      , 0.05      , 0.05      , ..., 0.05      , 0.05      ,
        0.05      ]])

In [253]:
print(lda_model.components_)
print(lda_model.components_.shape)

[[1.00001578e-01 1.00001244e-01 3.50170827e+03 ... 1.00004257e-01
  1.00001722e-01 1.00003979e-01]
 [1.00001847e-01 1.00001158e-01 1.00002229e-01 ... 1.00005861e-01
  1.00006065e-01 1.00002605e-01]
 [1.00002307e-01 1.00001528e-01 1.00007348e-01 ... 1.00005637e-01
  1.00002505e-01 1.00005427e-01]
 ...
 [3.51600411e+02 1.00001057e-01 1.00003859e-01 ... 1.00003895e-01
  1.00005142e-01 1.00004596e-01]
 [1.00001062e-01 1.00001649e-01 1.00006522e-01 ... 1.77619511e+03
  1.50652738e+02 7.53381835e+02]
 [1.00004033e-01 1.13513398e+03 1.00030595e-01 ... 1.00009276e-01
  1.00003667e-01 1.00003605e-01]]
(10, 1000)


In [258]:
terms = vectorizer.get_feature_names()

def get_topics(components, feature_names, n = 5):
    for idx, topic in enumerate(components):
        print('Topic %d' %(idx+1), [(feature_names[i], topic[i].round(2)) for i in topic.argsort()[: -n -1 : -1]])
        
get_topics(lda_model.components_, terms)

Topic 1 [('queensland', 7720.12), ('house', 6113.49), ('leave', 3849.71), ('2015', 3501.71), ('federal', 3120.93)]
Topic 2 [('police', 12092.44), ('sydney', 8393.29), ('melbourne', 7528.43), ('south', 6677.03), ('open', 5663.0)]
Topic 3 [('plan', 6033.16), ('change', 5874.27), ('year', 5586.42), ('school', 5465.06), ('coast', 5429.41)]
Topic 4 [('kill', 5851.6), ('woman', 5456.76), ('help', 5225.56), ('minister', 3973.22), ('child', 3838.44)]
Topic 5 [('death', 5935.06), ('women', 4232.53), ('indigenous', 4223.4), ('price', 3818.24), ('need', 3708.86)]
Topic 6 [('interview', 5924.98), ('record', 3987.87), ('league', 3911.12), ('fight', 3872.94), ('dead', 3503.84)]
Topic 7 [('charge', 8428.8), ('court', 7542.74), ('perth', 6456.53), ('murder', 6268.13), ('face', 5193.63)]
Topic 8 [('trump', 11966.41), ('australian', 11088.95), ('election', 7561.63), ('adelaide', 6758.36), ('canberra', 6112.23)]
Topic 9 [('home', 5674.38), ('market', 5545.86), ('north', 5142.38), ('warn', 5115.01), ('sta